name: Question 1

on:
  push:
    branches: [ question1 ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python
        
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'companydb'
        mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        
    - name: Wait for MySQL to start
      run: |
        sleep 15
        
    - name: Execute SQL scripts
      env:
        MYSQL_HOST: 'localhost'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: 'companydb'
      run: 
        python q1script.py