name: Question 1

on:
  push:
    branches: [ main ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h127.0.0.1 -uroot -ppassword123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MYSQL_HOST:     127.0.0.1
      MYSQL_USER:     root
      MYSQL_PASSWORD: password123

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Wait for MySQL to be healthy
        run: |
          until mysqladmin ping -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"; do
            echo "Waiting for MySQL…"
            sleep 5
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install mysql-connector-python

      - name: Run migrations
        run: python q1script.py
