name: Question 1
run-name: ${{ github.actor }} is testing out MySQL GitHub Actions 🚀
on: [push]

jobs:
  setup_mysql_database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Secret5555
          MYSQL_DATABASE: mysql
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be healthy…"
          for i in {1..30}; do
            if docker inspect --format='{{.State.Health.Status}}' ${{ job.services.mysql.id }} | grep -q healthy; then
              echo "MySQL is up!"
              break
            fi
            sleep 5
          done

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Deploy to Database
        run: |
          mysql \
            --host=127.0.0.1 \
            --user=root \
            --password=$MYSQL_ROOT_PASSWORD \
            mysql < create_projects_table.sql
